/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppTopicIdRouteRouteImport } from './routes/app/$topicId/route'
import { Route as AppTopicIdIndexRouteImport } from './routes/app/$topicId/index'
import { Route as AppTopicIdSubmitCompletedCardRouteImport } from './routes/app/$topicId/submit-completed-card'
import { Route as AppTopicIdInitiativesRouteImport } from './routes/app/$topicId/initiatives'
import { Route as AppTopicIdTabIdRouteImport } from './routes/app/$topicId/$tabId'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTopicIdRouteRoute = AppTopicIdRouteRouteImport.update({
  id: '/app/$topicId',
  path: '/app/$topicId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTopicIdIndexRoute = AppTopicIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppTopicIdRouteRoute,
} as any)
const AppTopicIdSubmitCompletedCardRoute =
  AppTopicIdSubmitCompletedCardRouteImport.update({
    id: '/submit-completed-card',
    path: '/submit-completed-card',
    getParentRoute: () => AppTopicIdRouteRoute,
  } as any)
const AppTopicIdInitiativesRoute = AppTopicIdInitiativesRouteImport.update({
  id: '/initiatives',
  path: '/initiatives',
  getParentRoute: () => AppTopicIdRouteRoute,
} as any)
const AppTopicIdTabIdRoute = AppTopicIdTabIdRouteImport.update({
  id: '/$tabId',
  path: '/$tabId',
  getParentRoute: () => AppTopicIdRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app/$topicId': typeof AppTopicIdRouteRouteWithChildren
  '/app': typeof AppIndexRoute
  '/app/$topicId/$tabId': typeof AppTopicIdTabIdRoute
  '/app/$topicId/initiatives': typeof AppTopicIdInitiativesRoute
  '/app/$topicId/submit-completed-card': typeof AppTopicIdSubmitCompletedCardRoute
  '/app/$topicId/': typeof AppTopicIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppIndexRoute
  '/app/$topicId/$tabId': typeof AppTopicIdTabIdRoute
  '/app/$topicId/initiatives': typeof AppTopicIdInitiativesRoute
  '/app/$topicId/submit-completed-card': typeof AppTopicIdSubmitCompletedCardRoute
  '/app/$topicId': typeof AppTopicIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app/$topicId': typeof AppTopicIdRouteRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/$topicId/$tabId': typeof AppTopicIdTabIdRoute
  '/app/$topicId/initiatives': typeof AppTopicIdInitiativesRoute
  '/app/$topicId/submit-completed-card': typeof AppTopicIdSubmitCompletedCardRoute
  '/app/$topicId/': typeof AppTopicIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/app/$topicId'
    | '/app'
    | '/app/$topicId/$tabId'
    | '/app/$topicId/initiatives'
    | '/app/$topicId/submit-completed-card'
    | '/app/$topicId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/app'
    | '/app/$topicId/$tabId'
    | '/app/$topicId/initiatives'
    | '/app/$topicId/submit-completed-card'
    | '/app/$topicId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/app/$topicId'
    | '/app/'
    | '/app/$topicId/$tabId'
    | '/app/$topicId/initiatives'
    | '/app/$topicId/submit-completed-card'
    | '/app/$topicId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AppTopicIdRouteRoute: typeof AppTopicIdRouteRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/$topicId': {
      id: '/app/$topicId'
      path: '/app/$topicId'
      fullPath: '/app/$topicId'
      preLoaderRoute: typeof AppTopicIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/$topicId/': {
      id: '/app/$topicId/'
      path: '/'
      fullPath: '/app/$topicId/'
      preLoaderRoute: typeof AppTopicIdIndexRouteImport
      parentRoute: typeof AppTopicIdRouteRoute
    }
    '/app/$topicId/submit-completed-card': {
      id: '/app/$topicId/submit-completed-card'
      path: '/submit-completed-card'
      fullPath: '/app/$topicId/submit-completed-card'
      preLoaderRoute: typeof AppTopicIdSubmitCompletedCardRouteImport
      parentRoute: typeof AppTopicIdRouteRoute
    }
    '/app/$topicId/initiatives': {
      id: '/app/$topicId/initiatives'
      path: '/initiatives'
      fullPath: '/app/$topicId/initiatives'
      preLoaderRoute: typeof AppTopicIdInitiativesRouteImport
      parentRoute: typeof AppTopicIdRouteRoute
    }
    '/app/$topicId/$tabId': {
      id: '/app/$topicId/$tabId'
      path: '/$tabId'
      fullPath: '/app/$topicId/$tabId'
      preLoaderRoute: typeof AppTopicIdTabIdRouteImport
      parentRoute: typeof AppTopicIdRouteRoute
    }
  }
}

interface AppTopicIdRouteRouteChildren {
  AppTopicIdTabIdRoute: typeof AppTopicIdTabIdRoute
  AppTopicIdInitiativesRoute: typeof AppTopicIdInitiativesRoute
  AppTopicIdSubmitCompletedCardRoute: typeof AppTopicIdSubmitCompletedCardRoute
  AppTopicIdIndexRoute: typeof AppTopicIdIndexRoute
}

const AppTopicIdRouteRouteChildren: AppTopicIdRouteRouteChildren = {
  AppTopicIdTabIdRoute: AppTopicIdTabIdRoute,
  AppTopicIdInitiativesRoute: AppTopicIdInitiativesRoute,
  AppTopicIdSubmitCompletedCardRoute: AppTopicIdSubmitCompletedCardRoute,
  AppTopicIdIndexRoute: AppTopicIdIndexRoute,
}

const AppTopicIdRouteRouteWithChildren = AppTopicIdRouteRoute._addFileChildren(
  AppTopicIdRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AppTopicIdRouteRoute: AppTopicIdRouteRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
